#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from centralwidget.ui on Wed Mar 17 14:17:55 2010
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_CentralWidget(object):
    def setupUi(self, CentralWidget):
        CentralWidget.setObjectName("CentralWidget")
        CentralWidget.resize(584, 447)
        self.vboxlayout = QtGui.QVBoxLayout(CentralWidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.commandLabel = QtGui.QLabel(CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel.sizePolicy().hasHeightForWidth())
        self.commandLabel.setSizePolicy(sizePolicy)
        self.commandLabel.setObjectName("commandLabel")
        self.hboxlayout.addWidget(self.commandLabel)
        self.commandLine = KLineEdit(CentralWidget)
        self.commandLine.setObjectName("commandLine")
        self.hboxlayout.addWidget(self.commandLine)
        self.startButton = KPushButton(CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setObjectName("startButton")
        self.hboxlayout.addWidget(self.startButton)
        self.attachButton = QtGui.QPushButton(CentralWidget)
        self.attachButton.setObjectName("attachButton")
        self.hboxlayout.addWidget(self.attachButton)
        self.stopButton = KPushButton(CentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName("stopButton")
        self.hboxlayout.addWidget(self.stopButton)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.filterLabel = QtGui.QLabel(CentralWidget)
        self.filterLabel.setObjectName("filterLabel")
        self.hboxlayout1.addWidget(self.filterLabel)
        self.filterLine = KLineEdit(CentralWidget)
        self.filterLine.setProperty("showClearButton", True)
        self.filterLine.setObjectName("filterLine")
        self.hboxlayout1.addWidget(self.filterLine)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.sysCallView = QtGui.QTableView(CentralWidget)
        self.sysCallView.setObjectName("sysCallView")
        self.vboxlayout1.addWidget(self.sysCallView)
        self.vboxlayout.addLayout(self.vboxlayout1)

        self.retranslateUi(CentralWidget)
        QtCore.QObject.connect(self.commandLine, QtCore.SIGNAL("returnPressed()"), self.startButton.animateClick)
        QtCore.QMetaObject.connectSlotsByName(CentralWidget)

    def retranslateUi(self, CentralWidget):
        self.commandLabel.setText(kdecore.i18n("Command:"))
        self.startButton.setText(kdecore.i18n("Start"))
        self.attachButton.setText(kdecore.i18n("Attach..."))
        self.stopButton.setText(kdecore.i18n("Stop"))
        self.stopButton.setShortcut(kdecore.i18n("Esc"))
        self.filterLabel.setText(kdecore.i18n("Filter:"))
        self.filterLine.setToolTip(kdecore.i18n("This line allows you to filter the results showed in the underneath table as you type"))

from PyKDE4.kdeui import KPushButton, KLineEdit
